### ISSUE TITLE
Notes on this curricula

### ISSUE THREAD

**Issue by aplassard** [CLuiz/cs_dev_plan#1]
First, a deeper course in data structures would be valuable, i.e  https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-851-advanced-data-structures-spring-2012/

Possibly a course on Operating System, but that is a bit tertiary. Hack the Kernel should be sufficient.

Topics that feel less import that others - Computer Networking, Computer Graphics, Computer Architecture/Organization.

It does look like you have basically all of the requirements for a variety of "specializations", i.e. http://csmajor.stanford.edu/ProgramSheets.shtml. You probably don't need to cover all of them immediately.

**Comment by CLuiz** [comment]
Thanks, added the data structures class and removed the graphics class.  I was considering an advanced os class, is there one you would suggest?  Otherwise I'll just grab one from mit/stanford. 
 Nice find on the stanford specializations sheet, I hadn't seen that. I'll add it to the page as a reference.
